// <auto-generated />
namespace BloomWCFService.Data.Migrations.BouquetDB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitialConfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialConfig));
        
        string IMigrationMetadata.Id
        {
            get { return "201904120342021_InitialConfig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
